"""Voting types for Team Fortress 2."""

from enum import Enum

class VoteTypes(Enum):
    """Vote types available when starting a vote."""
    KICK = "#TF_vote_kick_player_other"
    """Generic kick vote."""
    KICK_IDLE = "#TF_vote_kick_player_idle"
    """Idler kick vote."""
    KICK_CHEATING = "#TF_vote_kick_player_cheating"
    """Cheater kick vote."""
    KICK_SCAMMING = "#TF_vote_kick_player_scamming"
    """Scammer kick vote."""
    RESTART_GAME = "#TF_vote_restart_game"
    """Restart map vote."""
    CHANGE_LEVEL = "#TF_vote_changelevel"
    """Change map vote."""
    NEXT_LEVEL = "#TF_vote_nextlevel"
    """Set next map vote."""
    NEXT_LEVEL_CHOICES = "#TF_vote_nextlevel_choices"
    """End of map vote. This vote is not in the user vote menu."""
    SCRAMBLE_TEAMS = "#TF_vote_scramble_teams"
    """Scramble teams vote."""
    SCRAMBLE_TEAMS_AT_ROUND_END = "#TF_vote_should_scramble_round"
    """Scramble teams at round end vote. This vote is not in the user vote menu."""
    START_ROUND = "#TF_vote_td_start_round"
    """Start round vote. This vote is not in the user vote menu."""
    CHANGE_MVM_MISSION = "#TF_vote_changechallenge"
    """Change MVM mission vote."""
    ETERNAWEEN = "#TF_vote_eternaween"
    """Activate Halloween mode vote."""
    AUTOBALANCE_ENABLE = "#TF_vote_autobalance_enable"
    """Activate autobalance vote."""
    AUTOBALANCE_DISABLE = "#TF_vote_autobalance_disable"
    """Disable autobalance vote."""
    CLASSLIMIT_ENABLE = "#TF_vote_passed_classlimits_enable"
    """Activate class limit vote."""
    CLASSLIMIT_DISABLE = "#TF_vote_passed_classlimits_disable"
    """Disable class limit vote."""
    CUSTOM = "#TF_playerid_noteam"
    """Custom vote."""

class VotePassTypes(Enum):
    """Vote success types."""
    KICK = "#TF_vote_passed_kick_player"
    """Vote kick passed."""
    RESTART_GAME = "#TF_vote_passed_restart_game"
    """Restart vote passed."""
    CHANGE_LEVEL = "#TF_vote_passed_changelevel"
    """Change level vote passed."""
    NEXT_LEVEL = "#TF_vote_passed_nextlevel"
    """Set next level vote passed."""
    NEXT_LEVEL_EXTEND = "#TF_vote_passed_nextlevel_extend"
    """Current map has been extended."""
    SCRAMBLE_TEAMS = "#TF_vote_passed_scramble_teams"
    """Scramble teams vote passed."""
    START_ROUND = "#TF_vote_passed_td_start_round"
    """Start round vote passed."""
    CHANGE_MVM_MISSION = "#TF_vote_passed_changechallenge"
    """Change MVM mission vote passed."""
    ETERNAWEEN = "#TF_vote_passed_eternaween"
    """Halloween mode vote passed."""
    AUTOBALANCE_ENABLE = "#TF_vote_passed_autobalance_enable"
    """Activate autobalance vote passed."""
    AUTOBALANCE_DISABLE = "#TF_vote_passed_autobalance_disable"
    """Disable autobalance vote passed."""
    CLASSLIMIT_ENABLE = "#TF_vote_passed_classlimits_enable"
    """Activate class limit vote passed."""
    CLASSLIMIT_DISABLE = "#TF_vote_passed_classlimits_disable"
    """Disable class limit vote passed."""
    CUSTOM = "#TF_playerid_noteam"
    """Custom vote passed."""

class VoteFailedReason(Enum):
    """Vote failed reasons."""
    VOTE_FAILED_GENERIC = 0
    """Generic Vote Failed message"""
    VOTE_FAILED_YES_MUST_EXCEED_NO = 3
    """Yes votes must outnumber No votes"""
    VOTE_FAILED_QUORUM_FAILURE = 4
    """Not enough votes"""
